{% for project in k8s_projects %}
{% for ns_env in project.environments %}
{% set ns = project.name + '-' + ns_env -%}
{% for np_namespace in networkpolicy_namespaces %}
{% if np_namespace.name == ns  %}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-trusted
  namespace: {{ ns }}
spec:
  podSelector:
    matchLabels:
      network: trusted
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-untrusted
  namespace: {{ ns }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          - 100.64.0.0/10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-only
  namespace: {{ ns }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{% endif %}
{% endfor %}
{% endfor %}
{% endfor %}